/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Principal.Vistas;

import Principal.Controlador.MercanciaControlador;
import Principal.Modelos.MercanciaModelos;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import javax.swing.event.ListSelectionEvent;
import javax.swing.event.ListSelectionListener;

/**
 *
 * @author yaxkin-pc
 */
public class Mercancia extends javax.swing.JInternalFrame {

    /**
     * Creates new form Mercancia
     */
    public Mercancia() {
        initComponents();
        TBproductos.getTableHeader().setDefaultRenderer(new Principal.Modelos.EstiloTablaHeader());
        TBproductos.setDefaultRenderer(Object.class, new Principal.Modelos.EstiloTablaRenderer());
        limpiaCampos();
        this.setResizable(false);

        TBproductos.getSelectionModel().addListSelectionListener(new ListSelectionListener() {
            @Override
            public void valueChanged(ListSelectionEvent lse) {
                if (TBproductos.getSelectedRow() != -1) {
                    cambiaDatos();
                }
            }
        });
    }

    void cambiaDatos() {
        int fila = TBproductos.getSelectedRow();
        Codigo.setText(TBproductos.getValueAt(fila, 0).toString());
        Producto.setText(TBproductos.getValueAt(fila, 1).toString());
        Precio.setText(TBproductos.getValueAt(fila, 2).toString());
        Stock.setText(TBproductos.getValueAt(fila, 3).toString());

    }

    void limpiaCampos() {
        if (TBproductos.getSelectedRow() > -1) {
            TBproductos.removeRowSelectionInterval(TBproductos.getSelectedRow(), TBproductos.getSelectedRow());
        }
        Codigo.setText("");
        Producto.setText("");
        Precio.setText("");
        buscar.setText("");
        Stock.setText("");
        Principal.Modelos.MercanciaModelos.listar("");
    }

    void selecionaFila(String id) {
        for (int i = 0; i < TBproductos.getRowCount(); i++) {
            if (id.equals(TBproductos.getValueAt(i, 0))) {
                TBproductos.setRowSelectionInterval(i, i);
                break;
            }
        }

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        Codigo = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        Producto = new javax.swing.JTextField();
        Precio = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        Stock = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        Registrar = new javax.swing.JButton();
        Actualizar = new javax.swing.JButton();
        Eliminar = new javax.swing.JButton();
        EliminarBase = new javax.swing.JButton();
        Limpiar = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();
        buscar = new javax.swing.JTextField();
        jLabel20 = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        TBproductos = new javax.swing.JTable();

        setClosable(true);
        setMaximizable(true);
        setTitle("Mercancias");
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)), "Productos", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 11))); // NOI18N
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Codigo.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jPanel2.add(Codigo, new org.netbeans.lib.awtextra.AbsoluteConstraints(132, 35, 158, 29));

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel1.setText("Codigo de barras");
        jPanel2.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(15, 42, -1, -1));

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel2.setText("Nombre del Producto");
        jPanel2.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(331, 42, -1, -1));

        Producto.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jPanel2.add(Producto, new org.netbeans.lib.awtextra.AbsoluteConstraints(466, 35, 158, 29));

        Precio.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jPanel2.add(Precio, new org.netbeans.lib.awtextra.AbsoluteConstraints(761, 35, 158, 29));

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel3.setText("Precio");
        jPanel2.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(710, 42, -1, -1));

        Stock.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jPanel2.add(Stock, new org.netbeans.lib.awtextra.AbsoluteConstraints(466, 82, 158, 29));

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel4.setText("Stock");
        jPanel2.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(417, 89, -1, -1));

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 0, 940, 130));

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));
        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)), "Acciones", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 11))); // NOI18N
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Registrar.setBackground(new java.awt.Color(255, 255, 255));
        Registrar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/registrar.png"))); // NOI18N
        Registrar.setText("REGISTRAR");
        Registrar.setBorderPainted(false);
        Registrar.setContentAreaFilled(false);
        Registrar.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        Registrar.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        Registrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RegistrarActionPerformed(evt);
            }
        });
        jPanel3.add(Registrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(15, 16, -1, -1));

        Actualizar.setBackground(new java.awt.Color(255, 255, 255));
        Actualizar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/actualiza-base.png"))); // NOI18N
        Actualizar.setText("ACTUALIZAR");
        Actualizar.setBorderPainted(false);
        Actualizar.setContentAreaFilled(false);
        Actualizar.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        Actualizar.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        Actualizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ActualizarActionPerformed(evt);
            }
        });
        jPanel3.add(Actualizar, new org.netbeans.lib.awtextra.AbsoluteConstraints(142, 16, -1, -1));

        Eliminar.setBackground(new java.awt.Color(255, 255, 255));
        Eliminar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/eliminar-producto.png"))); // NOI18N
        Eliminar.setText("ELIMINAR");
        Eliminar.setBorderPainted(false);
        Eliminar.setContentAreaFilled(false);
        Eliminar.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        Eliminar.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        Eliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EliminarActionPerformed(evt);
            }
        });
        jPanel3.add(Eliminar, new org.netbeans.lib.awtextra.AbsoluteConstraints(263, 16, -1, -1));

        EliminarBase.setBackground(new java.awt.Color(255, 255, 255));
        EliminarBase.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/eliminar.png"))); // NOI18N
        EliminarBase.setText("ELIMINAR BASE");
        EliminarBase.setBorderPainted(false);
        EliminarBase.setContentAreaFilled(false);
        EliminarBase.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        EliminarBase.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        EliminarBase.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EliminarBaseActionPerformed(evt);
            }
        });
        jPanel3.add(EliminarBase, new org.netbeans.lib.awtextra.AbsoluteConstraints(378, 16, -1, -1));

        Limpiar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/escoba.png"))); // NOI18N
        Limpiar.setText(" LIMPIAR CAMPOS");
        Limpiar.setBorderPainted(false);
        Limpiar.setContentAreaFilled(false);
        Limpiar.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        Limpiar.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        Limpiar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LimpiarActionPerformed(evt);
            }
        });
        jPanel3.add(Limpiar, new org.netbeans.lib.awtextra.AbsoluteConstraints(493, 16, -1, -1));

        jPanel1.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 147, -1, 130));

        jPanel4.setBackground(new java.awt.Color(255, 255, 255));
        jPanel4.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)), "Busqueda", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 11))); // NOI18N
        jPanel4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        buscar.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        buscar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                buscarMouseClicked(evt);
            }
        });
        buscar.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                buscarKeyReleased(evt);
            }
        });
        jPanel4.add(buscar, new org.netbeans.lib.awtextra.AbsoluteConstraints(97, 49, 164, 31));

        jLabel20.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/buscar.png"))); // NOI18N
        jPanel4.add(jLabel20, new org.netbeans.lib.awtextra.AbsoluteConstraints(15, 35, -1, -1));

        jPanel1.add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(648, 147, 300, 128));

        jPanel5.setBackground(new java.awt.Color(255, 255, 255));
        jPanel5.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)), "Tabla", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 11))); // NOI18N
        jPanel5.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        TBproductos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Codigo Barras", "Nombre", "Precio", "Stock"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(TBproductos);

        jPanel5.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(5, 16, 920, 220));

        jPanel1.add(jPanel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 286, 940, 240));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 960, 530));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void buscarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_buscarMouseClicked
        limpiaCampos();
    }//GEN-LAST:event_buscarMouseClicked

    private void buscarKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_buscarKeyReleased
        buscar.setText(buscar.getText().toUpperCase());
       MercanciaModelos.listar(buscar.getText());
    }//GEN-LAST:event_buscarKeyReleased

    private void RegistrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RegistrarActionPerformed
        if (Codigo.getText().equals("") || Producto.getText().equals("")
                || Precio.getText().equals("") || Stock.getText().equals("")) {
            JOptionPane.showMessageDialog(this, "Todos los campos\nson obligatorios.", "Productos", 0,
                    new ImageIcon(getClass().getResource("/imagenes/informacion.png")));
        } else {
            Principal.Controlador.MercanciaControlador us = new MercanciaControlador();
            us.setPrimaryKey(Codigo.getText());
            us.setProducto(Producto.getText());
            us.setPrecio(Precio.getText());
            us.setStock(Stock.getText());
            int opcion = Principal.Modelos.MercanciaModelos.registrar(us);
            if (opcion != 0) {
                String id = Codigo.getText();
                selecionaFila(id);
                JOptionPane.showMessageDialog(this, "Registro éxitoso.", "Productos", 0,
                        new ImageIcon(getClass().getResource("/imagenes/verificar.png")));
            }
        }limpiaCampos();
    }//GEN-LAST:event_RegistrarActionPerformed

    private void ActualizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ActualizarActionPerformed
        if (TBproductos.getRowCount() > 0) {
            if (TBproductos.getSelectedRowCount() > 0) {
                if (Codigo.getText().equals("") || Producto.getText().equals("") || Stock.getText().equals("")
                        || Precio.getText().equals("")) {
                    JOptionPane.showMessageDialog(this, "Es necesario completar\ntodos los campos.", "Productos", 0,
                            new ImageIcon(getClass().getResource("/imagenes/informacion.png")));
                } else if (JOptionPane.showConfirmDialog(this, "Esta a punto de actualizar\nun registro.\n¿Desea continuar?", "Productos", JOptionPane.YES_NO_OPTION, 0,
                        new ImageIcon(getClass().getResource("/imagenes/advertencia.png"))) == JOptionPane.YES_OPTION) {
                    Principal.Controlador.MercanciaControlador us = new MercanciaControlador();
                    us.setPrimaryKey(Codigo.getText());
                    us.setProducto(Producto.getText());
                    us.setPrecio(Precio.getText());
                    us.setStock(Stock.getText());
                    int opcion = Principal.Modelos.MercanciaModelos.actualizar(us);
                    if (opcion != 0) {
                        String id = Codigo.getText();
                        limpiaCampos();
                        selecionaFila(id);
                        JOptionPane.showMessageDialog(this, "Registro actualizado.", "Productos", 0,
                                new ImageIcon(getClass().getResource("/imagenes/actualizado.png")));
                    }
                }
            } else {
                JOptionPane.showMessageDialog(this, "Seleccione un registro.", "Productos", 0,
                        new ImageIcon(getClass().getResource("/imagenes/informacion.png")));
            }

        } else {
            JOptionPane.showMessageDialog(this, "No hay registros\npara actualizar.", "Productos", 0,
                    new ImageIcon(getClass().getResource("/imagenes/informacion.png")));
        }
    }//GEN-LAST:event_ActualizarActionPerformed

    private void EliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EliminarActionPerformed
        if (TBproductos.getRowCount() > 0) {
            if (TBproductos.getSelectedRowCount() > 0) {
                if (JOptionPane.showConfirmDialog(this, "Esta a punto de eliminar\nun registro.\n¿Desea continuar?", "Productos", JOptionPane.YES_NO_OPTION, 0,
                        new ImageIcon(getClass().getResource("/imagenes/advertencia.png"))) == JOptionPane.YES_OPTION) {
                    int fila = TBproductos.getSelectedRow();
                    String id = TBproductos.getValueAt(fila, 0).toString();
                    int elimina = Principal.Modelos.MercanciaModelos.eliminar(id);
                    if (elimina != 0) {
                        limpiaCampos();
                        JOptionPane.showMessageDialog(this, "Registro eliminado.", "Productos", 0,
                                new ImageIcon(getClass().getResource("/imagenes/papelera.png")));
                    }
                }
            } else {
                JOptionPane.showMessageDialog(this, "Seleccione un registro.", "Productos", 0,
                        new ImageIcon(getClass().getResource("/imagenes/informacion.png")));
            }

        } else {
            JOptionPane.showMessageDialog(this, "No hay registros\npara eliminar.", "Productos", 0,
                    new ImageIcon(getClass().getResource("/imagenes/informacion.png")));
        }
    }//GEN-LAST:event_EliminarActionPerformed

    private void EliminarBaseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EliminarBaseActionPerformed
        if (TBproductos.getRowCount() > 0) {
            if (JOptionPane.showConfirmDialog(this, "Esta a punto de elimnar\ntodos los registros.\n¿Desea continuar?", "Productos", JOptionPane.YES_NO_OPTION, 0,
                    new ImageIcon(getClass().getResource("/imagenes/advertencia.png"))) == JOptionPane.YES_OPTION) {
                int eliminaT = Principal.Modelos.MercanciaModelos.eliminaTodos();
                if (eliminaT != 0) {
                    limpiaCampos();
                    JOptionPane.showMessageDialog(this, "Registros eliminados.", "Productos", 0,
                            new ImageIcon(getClass().getResource("/imagenes/borrar.png")));
                }
            }
        } else {
            JOptionPane.showMessageDialog(this, "No hay registros\npara eliminar.", "Productos", 0,
                    new ImageIcon(getClass().getResource("/imagenes/informacion.png")));
        }
    }//GEN-LAST:event_EliminarBaseActionPerformed

    private void LimpiarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LimpiarActionPerformed
        limpiaCampos();
    }//GEN-LAST:event_LimpiarActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Actualizar;
    public static javax.swing.JTextField Codigo;
    private javax.swing.JButton Eliminar;
    private javax.swing.JButton EliminarBase;
    private javax.swing.JButton Limpiar;
    private javax.swing.JTextField Precio;
    private javax.swing.JTextField Producto;
    private javax.swing.JButton Registrar;
    private javax.swing.JTextField Stock;
    public static javax.swing.JTable TBproductos;
    private javax.swing.JTextField buscar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
